In [143]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [144]:
iris=pd.read_csv("./IRIS.csv")

In [145]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [146]:
X=iris.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [147]:
y=iris["species"].values

In [148]:
y[y=='Iris-setosa']=0
y[y=='Iris-versicolor']=1
y[y=='Iris-virginica']=2

In [149]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=object)

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
X.shape

(150, 4)

In [152]:
y.shape

(150,)

In [153]:
dic={
    0:'Iris-setosa',
    1:'Iris-versicolor',
    2:'Iris-virginica'
}

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [155]:
def find_distance(pA, pB):
    return np.sum((pB - pA)**2)**0.5 

In [156]:
x_query= [[7.2, 3.6, 5.1, 2.5]]

In [157]:
def kNN(X, y, x_query, k = 5): #here we can keep k as default parameter
    
    """
           shape    Datatype 
    X - > (100, 2)  np array
    y - > (100,1) np array
    x_query -> (1,2) or 2, np array
    k -> scaler  int
    
    do knn for classification
    """
    
    m = X.shape[0] #total no. of examples we have 
    distances = [] 
    for i in range(m):
        dis = find_distance(x_query, X[i]) #
        distances.append((dis,y[i])) #so here we are appending list of tuple
        
    distances = sorted(distances) #after sorting 
    distances = distances[:k] #we are taking first k elements
    
    distances = np.array(distances) #storing distances in array
    labels = distances[:, 1] #for extracting labels
    
    
    
    uniq_label, counts =np.unique(labels, return_counts=True) #it find unique elements and return count and label

    pred = uniq_label[counts.argmax()] #here we are finding max occureded label
    
    
    return dic[int(pred)] #here we are converting int to float 

In [158]:
kNN(X,y,x_query,k=9)

'Iris-virginica'

In [159]:
X_test.shape

(30, 4)

In [160]:

predictions = []
for i in range(30):
    p = kNN(X_train , y_train, X_test[i], k=9)
    
    predictions.append(p)

In [161]:

y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=object)

In [162]:
p=np.array(predictions)
p[p=='Iris-setosa']=0
p[p=='Iris-versicolor']=1
p[p=='Iris-virginica']=2

p = ','.join(p)
p = np.fromstring( p, dtype=np.int, sep=',' )
p

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [163]:
(y_test[:30] == p)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [164]:
(y_test[:30] == predictions).sum()/len(predictions)

0.0

In [101]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
knn = KNeighborsClassifier(9)

In [50]:
knn.fit(X_train, y_train)

ValueError: Unknown label type: 'unknown'