In [1]:
pip

Note: you may need to restart the kernel to use updated packages.

Usage:   
  c:\users\lenovo\appdata\local\programs\python\python38-32\python.exe -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command 

In [2]:
pip install numpy

In [3]:
import numpy as np

In [4]:
l1=[1,2,3,4]

In [5]:
type(l1)

list

In [15]:
#creating arrrays
arr=np.array(l1)

In [16]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
np.shape

<function numpy.shape(a)>

In [11]:
arr.shape

(4,)

In [17]:
arr.ndim

1

In [54]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [55]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
arr2.ndim

2

In [57]:
arr2.shape

(3, 3)

In [58]:
arr2.dtype

dtype('float64')

In [61]:
l=range(10)
print(l)

range(0, 10)


In [62]:
[ i**2 for i in list(l)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [63]:
np.array(l)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [64]:
%timeit [ i**2 for i in list(l)]

8.75 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
%timeit np.array(l)**2 #%timeit it only works in jupyter notebook

48 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [66]:
arr


array([1, 2, 3, 4])

In [67]:
#all the elements are adde by 4
arr+4

array([5, 6, 7, 8])

In [78]:
arr2=arr+4

In [75]:
arr1=arr*4

In [76]:
arr-4

array([-3, -2, -1,  0])

In [80]:
arr1+arr2 #ele wise addition

array([ 9, 14, 19, 24])

In [81]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]],dtype=float) #use shift+tab

In [82]:
arr2+2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [83]:
np.random.ranint()

AttributeError: module 'numpy.random' has no attribute 'ranint'

In [85]:
arr1=np.random.randint(10,100,size=(5,5))

In [87]:
arr2=np.random.randint(10,100,size=(5,5))

In [88]:
arr1

array([[43, 41, 20, 43, 42],
       [10, 48, 35, 32, 89],
       [60, 66, 51, 70, 57],
       [14, 82, 51, 73, 23],
       [86, 95, 13, 17, 58]])

In [89]:
arr2

array([[70, 92, 31, 78, 61],
       [37, 76, 51, 46, 23],
       [14, 54, 71, 67, 63],
       [11, 86, 94, 29, 14],
       [98, 97, 43, 32, 90]])

# Operation on matrix

In [95]:
arr1+arr2

array([[113, 133,  51, 121, 103],
       [ 47, 124,  86,  78, 112],
       [ 74, 120, 122, 137, 120],
       [ 25, 168, 145, 102,  37],
       [184, 192,  56,  49, 148]])

In [96]:
#element wise multiplication
arr1*arr2

array([[3010, 3772,  620, 3354, 2562],
       [ 370, 3648, 1785, 1472, 2047],
       [ 840, 3564, 3621, 4690, 3591],
       [ 154, 7052, 4794, 2117,  322],
       [8428, 9215,  559,  544, 5220]])

In [97]:
arr1**2

array([[1849, 1681,  400, 1849, 1764],
       [ 100, 2304, 1225, 1024, 7921],
       [3600, 4356, 2601, 4900, 3249],
       [ 196, 6724, 2601, 5329,  529],
       [7396, 9025,  169,  289, 3364]], dtype=int32)

In [102]:
#matrix multiplication
np.dot(arr1,arr2)

array([[ 9396, 15924, 10692,  9171,  9208],
       [12040, 17843, 12078,  9109, 12377],
       [13712, 24839, 17878, 14987, 14501],
       [ 7785, 18783, 16088, 11134,  9045],
       [15588, 22922, 12526, 14298, 13708]])

In [103]:
#trying doing maatrix mul of three matrix

In [105]:
arr1.dot(arr2)

array([[ 9396, 15924, 10692,  9171,  9208],
       [12040, 17843, 12078,  9109, 12377],
       [13712, 24839, 17878, 14987, 14501],
       [ 7785, 18783, 16088, 11134,  9045],
       [15588, 22922, 12526, 14298, 13708]])

In [127]:
arr1*arr2

array([[3010, 3772,  620, 3354, 2562],
       [ 370, 3648, 1785, 1472, 2047],
       [ 840, 3564, 3621, 4690, 3591],
       [ 154, 7052, 4794, 2117,  322],
       [8428, 9215,  559,  544, 5220]])

In [128]:
arr1**arr2

array([[-2044005527,   -94459679,           0,  1421899977,           0],
       [          0,           0,  1272254651,           0,  -101875927],
       [  268435456,           0,  -281053349,           0, -1496964087],
       [ -588990464,           0,  1560815513,   118145449,   929076081],
       [          0,  2082038879,   142818741, -2018512383,           0]],
      dtype=int32)

# Array Slicing

In [107]:
arr1

array([[43, 41, 20, 43, 42],
       [10, 48, 35, 32, 89],
       [60, 66, 51, 70, 57],
       [14, 82, 51, 73, 23],
       [86, 95, 13, 17, 58]])

In [112]:
arr1[3,2]

array([], shape=(0, 1), dtype=int32)

In [113]:
arr1[3][2]

51

In [117]:
arr1[1:4, 1:5]

array([[48, 35, 32, 89],
       [66, 51, 70, 57],
       [82, 51, 73, 23]])

In [122]:
arr1[:,1:3]

array([[41, 20],
       [48, 35],
       [66, 51],
       [82, 51],
       [95, 13]])

In [123]:
#imaages are just numpy array

In [125]:
arr1[[1,3,4],:4]

array([[10, 48, 35, 32],
       [14, 82, 51, 73],
       [86, 95, 13, 17]])

# Brodcasting

In [126]:
#broadcasting

In [130]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [131]:
np.array([[1,2,3],[4,5,6],[7,8,9]])+ np.array([1,2,3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])